/* ═══════════════════════════════════════
   GAMES DATA — ZenMagma Platform | zenmagma.com
   Paths are relative from game.html → ../MathHelper/public/games/
═══════════════════════════════════════ */

const BASE = 'games/';

const CATEGORIES = [
  { id:'all',       label:'🎮 All Games',    color:'#6366f1' },
  { id:'runner',    label:'🏃 Runner',        color:'#f97316' },
  { id:'puzzle',    label:'🧩 Puzzle',        color:'#8b5cf6' },
  { id:'action',    label:'⚡ Action',        color:'#ef4444' },
  { id:'arcade',    label:'🕹️ Arcade',        color:'#3b82f6' },
  { id:'kids',      label:'🌈 Kids',          color:'#10b981' },
  { id:'strategy',  label:'♟️ Strategy',      color:'#ec4899' },
  { id:'adventure', label:'🗺️ Adventure',     color:'#a855f7' },
  { id:'classic',   label:'🎯 Classic',       color:'#f59e0b' },
  { id:'edu',       label:'📚 Education',     color:'#06b6d4' },
  { id:'sim',       label:'🏗️ Simulation',    color:'#84cc16' },
  { id:'quiz',      label:'🧠 Quizzes',       color:'#a855f7' },
];

const GAMES = [

  // ── QUIZBLAZE (FEATURED) ─────────────────────────────────────────────────────
  { id:'quizblaze',        slug:'quizblaze',        title:'QuizBlaze',            category:'quiz',      tags:['quiz','trivia','multiplayer','edu'], featured:true,  trending:true,  isNew:true,  plays:0,      rating:5.0, likes:0,     src:'quizblaze-v2.html',                emoji:'🧠', color:'#a855f7', desc:'Multiplayer trivia battles! 8 categories, live leaderboards, XP system, and bot opponents. Fastest answer wins more points!', controls:'Click answer buttons to respond', thumb:'' },

  // ── RUNNER ──────────────────────────────────────────────────────────────────
  { id:'temple-run',      slug:'temple-run',      title:'Temple Run',           category:'runner',    tags:['runner','action','popular'],      featured:true,  trending:true,  isNew:false, plays:248000, rating:4.8, likes:12400, src:BASE+'templerun.html',              emoji:'🏃', color:'#ef4444', desc:'Run through ancient temples! Jump, slide and dodge obstacles in this epic endless runner.',         controls:'← → Move | ↑ / SPACE Jump | ↓ Slide',   thumb:'assets/thumbs/temple-run.jpg',    videoPreview:'assets/previews/templerun.GIF.gif' },
  { id:'cosmic-run',      slug:'cosmic-run',      title:'Cosmic Run',           category:'runner',    tags:['runner','space','kids'],           featured:true,  trending:true,  isNew:false, plays:81000,  rating:4.6, likes:4200,  src:BASE+'47-cosmic-run.html',          emoji:'🚀', color:'#6366f1', desc:'Race through outer space dodging asteroids and energy barriers. 3 lives included!',               controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/cosmic-run.jpg' },
  { id:'pixel-dash',      slug:'pixel-dash',      title:'Pixel Dash',           category:'runner',    tags:['runner','retro','pixel'],          featured:false, trending:true,  isNew:false, plays:44000,  rating:4.3, likes:2100,  src:BASE+'46-pixel-dash.html',          emoji:'👾', color:'#f59e0b', desc:'8-bit retro endless runner. Jump and slide through pixel worlds!',                                controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/pixel-dash.jpg' },
  { id:'jungle-sprint',   slug:'jungle-sprint',   title:'Jungle Sprint',        category:'runner',    tags:['runner','jungle','adventure'],     featured:false, trending:false, isNew:false, plays:38000,  rating:4.4, likes:1900,  src:BASE+'48-jungle-sprint.html',       emoji:'🌿', color:'#10b981', desc:'Sprint through the jungle! Jump over logs and dodge wild obstacles.',                              controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/jungle-sprint.jpg' },
  { id:'highway-rush',    slug:'highway-rush',    title:'Highway Rush',         category:'runner',    tags:['runner','city','action'],          featured:false, trending:true,  isNew:false, plays:29000,  rating:4.2, likes:1450,  src:BASE+'49-highway-rush.html',        emoji:'🛹', color:'#3b82f6', desc:'Dodge traffic on a skateboard! Hit the streets and dodge everything in your way.',                 controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/highway-rush.jpg' },
  { id:'neon-runner',     slug:'neon-runner',     title:'Neon Runner',          category:'runner',    tags:['runner','cyberpunk','neon'],       featured:false, trending:true,  isNew:false, plays:55000,  rating:4.6, likes:3200,  src:BASE+'51-neon-runner.html',         emoji:'⚡', color:'#a855f7', desc:'Speed through neon-lit cyberpunk streets. Flash past glowing barriers!',                           controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/neon-runner.jpg' },
  { id:'desert-racer',    slug:'desert-racer',    title:'Desert Racer',         category:'runner',    tags:['runner','desert','action'],        featured:false, trending:false, isNew:true,  plays:18000,  rating:4.0, likes:760,   src:BASE+'52-desert-racer.html',        emoji:'🏜️', color:'#f97316', desc:'Race across scorching desert sands! Dodge cacti and sandstorm obstacles.',                         controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/desert-racer.jpg' },
  { id:'thunder-bird',    slug:'thunder-bird',    title:'Thunder Bird',         category:'action',    tags:['runner','storm','action'],         featured:false, trending:true,  isNew:false, plays:27000,  rating:4.4, likes:1340,  src:BASE+'54-thunder-bird.html',        emoji:'🦅', color:'#7c3aed', desc:'Soar as a mighty eagle through thunderstorms. Dodge lightning and ride wind currents!',            controls:'↑ / SPACE Fly Up | ↓ Dive',              thumb:'assets/thumbs/thunder-bird.jpg' },
  { id:'robot-run',       slug:'robot-run',       title:'Robot Run',            category:'kids',      tags:['runner','robot','kids'],           featured:false, trending:false, isNew:false, plays:42000,  rating:4.5, likes:2100,  src:BASE+'55-robot-run.html',           emoji:'🤖', color:'#6366f1', desc:'A cute robot dashes through the factory! Avoid conveyor belt hazards.',                           controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/robot-run.jpg' },
  { id:'forest-runner',   slug:'forest-runner',   title:'Forest Runner',        category:'runner',    tags:['runner','forest','nature'],        featured:false, trending:false, isNew:false, plays:15000,  rating:4.0, likes:620,   src:BASE+'33-forest-runner.html',       emoji:'🌲', color:'#16a34a', desc:'Run through a magical forest! Avoid tree roots, rocks and fallen logs.',                          controls:'↑ / SPACE Jump | ↓ Slide',               thumb:'assets/thumbs/forest-runner.jpg' },
  { id:'sky-glider',      slug:'sky-glider',      title:'Sky Glider',           category:'adventure', tags:['runner','sky','adventure'],        featured:false, trending:false, isNew:true,  plays:21000,  rating:4.1, likes:980,   src:BASE+'50-sky-glider.html',          emoji:'🪂', color:'#14b8a6', desc:'Soar through the clouds on a hang glider. Avoid storm clouds and obstacles!',                      controls:'↑ / SPACE Fly Up | ↓ Dive',thumb:'assets/thumbs/sky-glider.jpg' },
  { id:'deep-sea-dash',   slug:'deep-sea-dash',   title:'Deep Sea Dash',        category:'adventure', tags:['runner','ocean','underwater'],     featured:false, trending:false, isNew:false, plays:33000,  rating:4.3, likes:1670,  src:BASE+'53-deep-sea-dash.html',       emoji:'🌊', color:'#0ea5e9', desc:'Dive deep into the ocean! Dodge coral reefs and jellyfish.',                                      controls:'↑ / SPACE Ascend | ↓ Dive',thumb:'assets/thumbs/deep-sea-dash.jpg' },
  { id:'ancient-temple',  slug:'ancient-temple',  title:'Ancient Temple',       category:'adventure', tags:['runner','adventure','temple'],     featured:false, trending:false, isNew:false, plays:24000,  rating:4.2, likes:1100,  src:BASE+'45-ancient-temple.html',      emoji:'🏛️', color:'#b45309', desc:'Navigate the booby-trapped ancient temple! Dodge spikes, pits and rolling boulders.',            controls:'← → Move | ↑ Jump | ↓ Slide',thumb:'assets/thumbs/ancient-temple.jpg' },

  // ── PUZZLE ──────────────────────────────────────────────────────────────────
  { id:'candy-cascade',   slug:'candy-cascade',   title:'Candy Cascade',        category:'puzzle',    tags:['puzzle','match3','kids'],          featured:true,  trending:true,  isNew:false, plays:156000, rating:4.7, likes:8900,  src:BASE+'01-color-cascade.html',       emoji:'🍬', color:'#ec4899', desc:'Match 3 or more same-colored candies! Make combos for mega points.',                              controls:'Click to select and swap candies', thumb:'assets/thumbs/candy-cascade.jpg' },
  { id:'gravity-flip',    slug:'gravity-flip',    title:'Gravity Flip!',        category:'puzzle',    tags:['puzzle','gravity','platformer'],   featured:true,  trending:false, isNew:false, plays:67000,  rating:4.5, likes:3100,  src:BASE+'08-gravity-blocks.html',      emoji:'🔄', color:'#8b5cf6', desc:'Flip gravity to collect stars! Navigate platforms by flipping the world upside down.',            controls:'← → Move | ↑↓ / SPACE Flip Gravity',thumb:'assets/thumbs/gravity-flip.jpg' },
  { id:'color-flood',     slug:'color-flood',     title:'Color Flood',          category:'puzzle',    tags:['puzzle','color','strategy'],       featured:false, trending:true,  isNew:false, plays:91000,  rating:4.6, likes:5600,  src:BASE+'11-color-flood.html',         emoji:'🎨', color:'#10b981', desc:'Flood the board with one color! Strategically expand your territory.',                            controls:'Click colored buttons to flood', thumb:'assets/thumbs/color-flood.jpg' },
  { id:'memory-matrix',   slug:'memory-matrix',   title:'Memory Matrix',        category:'puzzle',    tags:['puzzle','memory','brain'],         featured:false, trending:false, isNew:false, plays:78000,  rating:4.7, likes:4800,  src:BASE+'05-memory-matrix.html',       emoji:'🧠', color:'#8b5cf6', desc:'Test your memory! Match pairs of cards before time runs out.',                                    controls:'Click to flip cards and find matches',thumb:'assets/thumbs/memory-matrix.jpg' },
  { id:'number-path',     slug:'number-path',     title:'Number Path',          category:'puzzle',    tags:['puzzle','numbers','math'],         featured:false, trending:false, isNew:false, plays:34000,  rating:4.2, likes:1800,  src:BASE+'02-number-path.html',         emoji:'🔢', color:'#3b82f6', desc:'Connect numbers in the correct order to complete each path puzzle.',                              controls:'Click numbers in order 1→2→3...',thumb:'assets/thumbs/number-path.jpg' },
  { id:'pipe-connect',    slug:'pipe-connect',    title:'Pipe Connect',         category:'puzzle',    tags:['puzzle','logic','connect'],        featured:false, trending:false, isNew:false, plays:28000,  rating:4.1, likes:1200,  src:BASE+'04-pipe-connect.html',        emoji:'🔧', color:'#f97316', desc:'Connect all the pipes before the water flows! Rotate pieces to create a path.',                  controls:'Click pipe pieces to rotate them',thumb:'assets/thumbs/pipe-connect.jpg' },
  { id:'tile-slide',      slug:'tile-slide',      title:'Tile Slide',           category:'puzzle',    tags:['puzzle','slide','classic'],        featured:false, trending:false, isNew:false, plays:19000,  rating:3.9, likes:810,   src:BASE+'10-tile-slide.html',          emoji:'🧩', color:'#f59e0b', desc:'Classic sliding tile puzzle. Arrange the pieces in the right order!',                            controls:'Click tiles adjacent to empty space',thumb:'assets/thumbs/tile-slide.jpg' },
  { id:'pattern-lock',    slug:'pattern-lock',    title:'Pattern Lock',         category:'puzzle',    tags:['puzzle','pattern','memory'],       featured:false, trending:false, isNew:false, plays:22000,  rating:4.0, likes:980,   src:BASE+'09-pattern-lock.html',        emoji:'🔐', color:'#ec4899', desc:'Memorize and recreate patterns! Gets harder with every level.',                                  controls:'Click dots to draw the pattern',thumb:'assets/thumbs/pattern-lock.jpg' },
  { id:'shadow-match',    slug:'shadow-match',    title:'Shadow Match',         category:'puzzle',    tags:['puzzle','visual','kids'],          featured:false, trending:false, isNew:false, plays:31000,  rating:4.3, likes:1500,  src:BASE+'03-shadow-match.html',        emoji:'🌑', color:'#64748b', desc:'Match shapes to their shadows before time runs out. Visual puzzle fun!',                        controls:'Drag shapes onto matching shadows',thumb:'assets/thumbs/shadow-match.jpg' },
  { id:'2048',            slug:'2048',            title:'2048',                 category:'puzzle',    tags:['puzzle','numbers','math'],         featured:false, trending:true,  isNew:false, plays:120000, rating:4.8, likes:9200,  src:BASE+'2048.html',                   emoji:'🔢', color:'#f59e0b', desc:'Slide and merge numbered tiles to reach 2048! The classic brain puzzle.',                        controls:'Arrow keys to slide tiles', thumb:'assets/thumbs/2048.jpg' },
  { id:'word-jumble',     slug:'word-jumble',     title:'Word Jumble',          category:'puzzle',    tags:['puzzle','words','language'],       featured:false, trending:false, isNew:false, plays:26000,  rating:4.1, likes:1300,  src:BASE+'06-word-jumble.html',         emoji:'🔤', color:'#0ea5e9', desc:'Unscramble jumbled letters to find the hidden word! Race against the clock.',                     controls:'Click letters to unscramble',thumb:'assets/thumbs/word-jumble.jpg' },
  { id:'light-refract',   slug:'light-refract',   title:'Light Refract',        category:'puzzle',    tags:['puzzle','light','logic'],          featured:false, trending:false, isNew:false, plays:18000,  rating:4.2, likes:890,   src:BASE+'07-light-refract.html',       emoji:'🔦', color:'#fbbf24', desc:'Reflect laser beams using mirrors! Direct light to all targets to beat each level.',             controls:'Click and drag mirrors to rotate',thumb:'assets/thumbs/light-refract.jpg' },
  { id:'bridge-builder',  slug:'bridge-builder',  title:'Bridge Builder',       category:'puzzle',    tags:['puzzle','physics','build'],        featured:false, trending:true,  isNew:false, plays:52000,  rating:4.5, likes:2900,  src:BASE+'12-bridge-builder.html',      emoji:'🌉', color:'#78350f', desc:'Build bridges that can hold the weight of crossing vehicles! Physics-based puzzle.',            controls:'Click and drag to place bridge pieces',thumb:'assets/thumbs/bridge-builder.jpg' },
  { id:'hidden-stars',    slug:'hidden-stars',    title:'Hidden Stars',         category:'puzzle',    tags:['puzzle','hidden','visual'],        featured:false, trending:false, isNew:false, plays:33000,  rating:4.3, likes:1700,  src:BASE+'13-hidden-stars.html',        emoji:'⭐', color:'#f59e0b', desc:'Find all the hidden stars in the picture! Look carefully and spot them all.',                    controls:'Click to reveal hidden stars',thumb:'assets/thumbs/hidden-stars.jpg' },
  { id:'logic-gates',     slug:'logic-gates',     title:'Logic Gates',          category:'puzzle',    tags:['puzzle','logic','edu'],            featured:false, trending:false, isNew:false, plays:14000,  rating:4.0, likes:680,   src:BASE+'14-logic-gates.html',         emoji:'⚙️', color:'#475569', desc:'Wire up logic gates to solve circuits! Learn about AND, OR and NOT gates.',                      controls:'Click to connect gates and toggle inputs',thumb:'assets/thumbs/logic-gates.jpg' },
  { id:'mosaic-maker',    slug:'mosaic-maker',    title:'Mosaic Maker',         category:'puzzle',    tags:['puzzle','art','color'],            featured:false, trending:false, isNew:false, plays:21000,  rating:4.1, likes:1050,  src:BASE+'15-mosaic-maker.html',        emoji:'🎭', color:'#ec4899', desc:'Fill in the numbered grid to create beautiful mosaic pictures!',                                 controls:'Click squares to paint by number',thumb:'assets/thumbs/mosaic-maker.jpg' },
  { id:'spot-difference', slug:'spot-difference', title:'Spot the Difference',  category:'puzzle',    tags:['puzzle','visual','kids'],          featured:false, trending:true,  isNew:false, plays:74000,  rating:4.4, likes:4200,  src:BASE+'spot-the-difference.html',    emoji:'🔍', color:'#7c3aed', desc:'Find all differences between two pictures! How sharp are your eyes?',                            controls:'Click on differences you spot',thumb:'assets/thumbs/spot-difference.jpg' },
  { id:'crystal-crusher', slug:'crystal-crusher', title:'Crystal Crusher',      category:'puzzle',    tags:['puzzle','match3','action'],        featured:false, trending:false, isNew:false, plays:41000,  rating:4.3, likes:2200,  src:BASE+'27-crystal-crusher.html',     emoji:'💎', color:'#06b6d4', desc:'Blast and match glowing crystals! Create chain reactions for massive scores.',                   controls:'Click to shoot crystals',thumb:'assets/thumbs/crystal-crusher.jpg' },
  { id:'maze-general',    slug:'maze-general',    title:'Maze Runner',          category:'puzzle',    tags:['puzzle','maze','adventure'],       featured:false, trending:false, isNew:false, plays:38000,  rating:4.2, likes:1900,  src:BASE+'83-maze-general.html',        emoji:'🌀', color:'#8b5cf6', desc:'Navigate through increasingly complex mazes! Find the exit before time runs out.',               controls:'Arrow keys or WASD to move',thumb:'assets/thumbs/maze-general.jpg' },

  // ── ACTION ──────────────────────────────────────────────────────────────────
  { id:'star-blaster',    slug:'star-blaster',    title:'Star Blaster',         category:'action',    tags:['action','space','shoot'],          featured:false, trending:true,  isNew:false, plays:112000, rating:4.8, likes:7200,  src:BASE+'16-star-blaster.html',        emoji:'💥', color:'#ef4444', desc:'Defend the galaxy from alien invaders! Blast through waves of enemies.',                         controls:'← → Move | SPACE Shoot', thumb:'assets/thumbs/star-blaster.jpg' },
  { id:'ninja-slash',     slug:'ninja-slash',     title:'Ninja Slash',          category:'action',    tags:['action','ninja','slash'],          featured:false, trending:true,  isNew:false, plays:67000,  rating:4.5, likes:3800,  src:BASE+'17-ninja-slash.html',         emoji:'🥷', color:'#1e293b', desc:'Become the ultimate ninja! Slash enemies and dodge attacks.',                                    controls:'Mouse / Touch to slash',thumb:'assets/thumbs/ninja-slash.jpg' },
  { id:'zombie-rush',     slug:'zombie-rush',     title:'Zombie Rush',          category:'action',    tags:['action','zombie','defend'],        featured:false, trending:false, isNew:false, plays:58000,  rating:4.4, likes:3100,  src:BASE+'20-zombie-rush.html',         emoji:'🧟', color:'#4d7c0f', desc:'Survive the zombie apocalypse! Defend your base from endless waves.',                            controls:'Mouse to aim and shoot',thumb:'assets/thumbs/zombie-rush.jpg' },
  { id:'volcano-escape',  slug:'volcano-escape',  title:'Volcano Escape',       category:'action',    tags:['action','adventure','escape'],     featured:false, trending:false, isNew:false, plays:24000,  rating:4.0, likes:1100,  src:BASE+'25-volcano-escape.html',      emoji:'🌋', color:'#dc2626', desc:'Escape the erupting volcano! Run, jump and avoid falling lava rocks.',                          controls:'← → Move | ↑ Jump',thumb:'assets/thumbs/volcano-escape.jpg' },
  { id:'dragon-rider',    slug:'dragon-rider',    title:'Dragon Rider',         category:'action',    tags:['action','dragon','adventure'],     featured:false, trending:true,  isNew:false, plays:88000,  rating:4.6, likes:5400,  src:BASE+'43-dragon-rider.html',        emoji:'🐉', color:'#b45309', desc:'Ride a mighty dragon through treacherous skies! Breathe fire at enemies.',                       controls:'Mouse / Touch to control direction', thumb:'assets/thumbs/dragon-rider.jpg' },
  { id:'magnet-warrior',  slug:'magnet-warrior',  title:'Magnet Warrior',       category:'action',    tags:['action','magnet','puzzle'],        featured:false, trending:false, isNew:false, plays:19000,  rating:4.1, likes:920,   src:BASE+'22-magnet-warrior.html',      emoji:'🧲', color:'#dc2626', desc:'Control magnetic forces to defeat enemies! Attract and repel your way to victory.',              controls:'Mouse to aim | SPACE to switch polarity',thumb:'assets/thumbs/magnet-warrior.jpg' },
  { id:'storm-archer',    slug:'storm-archer',    title:'Storm Archer',         category:'action',    tags:['action','archery','shoot'],        featured:false, trending:false, isNew:false, plays:31000,  rating:4.2, likes:1600,  src:BASE+'23-storm-archer.html',        emoji:'🏹', color:'#7c3aed', desc:'Fire arrows through raging storms! Aim carefully with wind effects.',                            controls:'Mouse to aim and shoot',thumb:'assets/thumbs/storm-archer.jpg' },
  { id:'cyber-punch',     slug:'cyber-punch',     title:'Cyber Punch',          category:'action',    tags:['action','fighting','cyber'],       featured:false, trending:false, isNew:false, plays:44000,  rating:4.3, likes:2300,  src:BASE+'24-cyber-punch.html',         emoji:'🤜', color:'#6366f1', desc:'Street brawler in a neon cyberpunk city! Punch and kick through waves of enemies.',              controls:'← → Move | A Punch | S Kick | ↑ Jump',thumb:'assets/thumbs/cyber-punch.jpg' },
  { id:'ice-sniper',      slug:'ice-sniper',      title:'Ice Sniper',           category:'action',    tags:['action','sniper','shoot'],         featured:false, trending:false, isNew:false, plays:27000,  rating:4.0, likes:1300,  src:BASE+'26-ice-sniper.html',          emoji:'🎯', color:'#0ea5e9', desc:'Snipe targets through blizzard conditions! Account for wind and distance.',                      controls:'Mouse to aim and click to shoot',thumb:'assets/thumbs/ice-sniper.jpg' },
  { id:'drone-strike',    slug:'drone-strike',    title:'Drone Strike',         category:'action',    tags:['action','drone','shoot'],          featured:false, trending:true,  isNew:false, plays:48000,  rating:4.4, likes:2600,  src:BASE+'28-drone-strike.html',        emoji:'🚁', color:'#374151', desc:'Pilot your combat drone through enemy territory! Destroy targets before they destroy you.',      controls:'WASD / Arrows to fly | SPACE to shoot',thumb:'assets/thumbs/drone-strike.jpg' },
  { id:'pirate-cannon',   slug:'pirate-cannon',   title:'Pirate Cannon',        category:'action',    tags:['action','pirate','shoot'],         featured:false, trending:false, isNew:false, plays:36000,  rating:4.2, likes:1800,  src:BASE+'29-pirate-cannon.html',       emoji:'💣', color:'#b45309', desc:'Fire cannonballs at enemy ships! Aim perfectly and sink their fleet.',                           controls:'Mouse to aim | Click to fire',thumb:'assets/thumbs/pirate-cannon.jpg' },
  { id:'bug-zapper',      slug:'bug-zapper',      title:'Bug Zapper',           category:'action',    tags:['action','bugs','reflex'],          featured:false, trending:false, isNew:false, plays:22000,  rating:3.9, likes:1050,  src:BASE+'30-bug-zapper.html',          emoji:'🐛', color:'#65a30d', desc:'Zap bugs before they invade your garden! Fast reflexes needed.',                                 controls:'Click / tap bugs to zap them',thumb:'assets/thumbs/bug-zapper.jpg' },
  { id:'fire-fighter',    slug:'fire-fighter',    title:'Fire Fighter',         category:'action',    tags:['action','rescue','fire'],          featured:false, trending:false, isNew:false, plays:29000,  rating:4.1, likes:1400,  src:BASE+'21-fire-fighter.html',        emoji:'🚒', color:'#dc2626', desc:'Battle blazing fires and rescue survivors! Manage your water supply carefully.',                 controls:'← → Move | SPACE Spray water',thumb:'assets/thumbs/fire-fighter.jpg' },
  { id:'ninja-rooftop',   slug:'ninja-rooftop',   title:'Ninja Rooftop',        category:'action',    tags:['action','ninja','parkour'],        featured:false, trending:false, isNew:false, plays:44000,  rating:4.3, likes:2400,  src:BASE+'41-ninja-rooftop.html',       emoji:'🥷', color:'#1e293b', desc:'Run across rooftops as a ninja! Jump between buildings and defeat enemies.',                     controls:'← → Move | ↑ Jump | A Attack',thumb:'assets/thumbs/ninja-rooftop.jpg' },
  { id:'magic-mushroom',  slug:'magic-mushroom',  title:'Magic Mushroom',       category:'adventure', tags:['adventure','platform','kids'],     featured:false, trending:false, isNew:false, plays:19000,  rating:4.1, likes:890,   src:BASE+'37-magic-mushroom.html',      emoji:'🍄', color:'#dc2626', desc:'Explore a magical mushroom forest world! Collect coins and power-ups.',                         controls:'← → Move | ↑ Jump',thumb:'assets/thumbs/magic-mushroom.jpg' },

  // ── ARCADE / CLASSIC ────────────────────────────────────────────────────────
  { id:'flappy-bird',     slug:'flappy-bird',     title:'Flappy Bird',          category:'arcade',    tags:['arcade','classic','birds'],        featured:true,  trending:true,  isNew:false, plays:320000, rating:4.5, likes:18000, src:BASE+'flappybird.html',             emoji:'🐦', color:'#f59e0b', desc:'The legendary Flappy Bird! Tap to fly through pipes without crashing.',                         controls:'Click / SPACE to flap', thumb:'assets/thumbs/flappy-bird.jpg' },
  { id:'snake-reborn',    slug:'snake-reborn',    title:'Snake Reborn',         category:'arcade',    tags:['arcade','snake','classic'],        featured:false, trending:true,  isNew:false, plays:145000, rating:4.7, likes:9800,  src:BASE+'98-snake-reborn.html',        emoji:'🐍', color:'#16a34a', desc:'The classic snake game reimagined! Eat food, grow longer, avoid yourself.',                      controls:'Arrow keys to change direction', thumb:'assets/thumbs/snake-reborn.jpg' },
  { id:'snake-classic',   slug:'snake-classic',   title:'Snake Classic',        category:'classic',   tags:['classic','snake','arcade'],        featured:false, trending:false, isNew:false, plays:98000,  rating:4.4, likes:5600,  src:BASE+'snake.html',                  emoji:'🐍', color:'#22c55e', desc:'The original snake game. Eat apples and grow without hitting yourself!',                        controls:'Arrow keys to steer',thumb:'assets/thumbs/snake-classic.jpg' },
  { id:'bubble-blitz',    slug:'bubble-blitz',    title:'Bubble Blitz',         category:'arcade',    tags:['arcade','bubbles','kids'],         featured:false, trending:false, isNew:false, plays:72000,  rating:4.4, likes:4100,  src:BASE+'18-bubble-blitz.html',        emoji:'🫧', color:'#0ea5e9', desc:'Pop bubbles before they reach the top! Match colors to burst whole groups.',                     controls:'Click to shoot bubbles',thumb:'assets/thumbs/bubble-blitz.jpg' },
  { id:'pong-remix',      slug:'pong-remix',      title:'Pong Remix',           category:'classic',   tags:['classic','pong','arcade'],         featured:false, trending:false, isNew:false, plays:39000,  rating:4.0, likes:1700,  src:BASE+'96-pong-remix.html',          emoji:'🏓', color:'#475569', desc:'The original pong game remixed with power-ups and new game modes!',                             controls:'Mouse or W/S keys',thumb:'assets/thumbs/pong-remix.jpg' },
  { id:'breakout-plus',   slug:'breakout-plus',   title:'Breakout Plus',        category:'classic',   tags:['classic','breakout','arcade'],     featured:false, trending:false, isNew:false, plays:51000,  rating:4.3, likes:2900,  src:BASE+'97-breakout-plus.html',       emoji:'🧱', color:'#f97316', desc:'Break all the bricks before losing all your balls! Classic arcade action.',                     controls:'← → / Mouse to move paddle',thumb:'assets/thumbs/breakout-plus.jpg' },
  { id:'pinball-pro',     slug:'pinball-pro',     title:'Pinball Pro',          category:'arcade',    tags:['arcade','pinball','classic'],      featured:false, trending:true,  isNew:false, plays:62000,  rating:4.5, likes:3600,  src:BASE+'93-pinball-pro.html',         emoji:'⚡', color:'#6366f1', desc:'Full-featured pinball machine in your browser! Hit targets and score big.',                     controls:'Z / X or ← → for flippers',thumb:'assets/thumbs/pinball-pro.jpg' },
  { id:'whack-a-mole',    slug:'whack-a-mole',    title:'Whack-a-Mole',         category:'arcade',    tags:['arcade','kids','reflex'],          featured:false, trending:false, isNew:false, plays:84000,  rating:4.4, likes:5100,  src:BASE+'94-whack-a-mole.html',        emoji:'🔨', color:'#78350f', desc:'Whack the moles before they go back underground! Test your reflexes.',                         controls:'Click / tap the moles',thumb:'assets/thumbs/whack-a-mole.jpg' },
  { id:'whack-a-mole2',   slug:'whack-a-mole2',   title:'Whack-a-Mole 2',       category:'arcade',    tags:['arcade','kids','reflex'],          featured:false, trending:false, isNew:false, plays:61000,  rating:4.3, likes:3400,  src:BASE+'whackamole.html',             emoji:'🐹', color:'#92400e', desc:'Another whack-a-mole variant with faster moles and bonus rounds!',                              controls:'Click / tap the moles',thumb:'assets/thumbs/whack-a-mole2.jpg' },
  { id:'tictactoe',       slug:'tictactoe',       title:'Tic Tac Toe',          category:'classic',   tags:['classic','strategy','2player'],    featured:false, trending:false, isNew:false, plays:48000,  rating:4.1, likes:2400,  src:BASE+'tictactoe.html',              emoji:'⭕', color:'#0ea5e9', desc:'Classic Tic Tac Toe for 2 players or vs computer. Who gets 3 in a row?',                       controls:'Click squares to place mark',thumb:'assets/thumbs/tictactoe.jpg' },
  { id:'coin-grab',       slug:'coin-grab',       title:'Coin Grab',            category:'arcade',    tags:['arcade','coins','collect'],        featured:false, trending:false, isNew:false, plays:25000,  rating:3.9, likes:1100,  src:BASE+'89-coin-grab.html',           emoji:'🪙', color:'#f59e0b', desc:'Grab as many coins as you can! Avoid obstacles and collect bonuses.',                           controls:'← → / Mouse to move',thumb:'assets/thumbs/coin-grab.jpg' },
  { id:'spin-match',      slug:'spin-match',      title:'Spin Match',           category:'arcade',    tags:['arcade','match','spin'],           featured:false, trending:false, isNew:false, plays:21000,  rating:3.8, likes:920,   src:BASE+'90-spin-match.html',          emoji:'🌀', color:'#8b5cf6', desc:'Spin the wheel and match colors! Time your spins perfectly to score.',                          controls:'Click / Space to spin',thumb:'assets/thumbs/spin-match.jpg' },
  { id:'stack-jump',      slug:'stack-jump',      title:'Stack Jump',           category:'arcade',    tags:['arcade','stack','platform'],       featured:false, trending:false, isNew:false, plays:38000,  rating:4.2, likes:2100,  src:BASE+'88-stack-jump.html',          emoji:'📦', color:'#f97316', desc:'Stack blocks as high as you can! Time your jumps perfectly to build the tallest tower.',        controls:'Click / SPACE to jump and stack',thumb:'assets/thumbs/stack-jump.jpg' },
  { id:'bubble-wrap',     slug:'bubble-wrap',     title:'Bubble Wrap',          category:'arcade',    tags:['arcade','relax','pop'],            featured:false, trending:false, isNew:true,  plays:88000,  rating:4.6, likes:5800,  src:BASE+'91-bubble-wrap.html',         emoji:'🫧', color:'#06b6d4', desc:'Pop every bubble on the sheet! The most satisfying game ever made.',                            controls:'Click / tap to pop bubbles',thumb:'assets/thumbs/bubble-wrap.jpg' },
  { id:'duck-shooter',    slug:'duck-shooter',    title:'Duck Shooter',         category:'arcade',    tags:['arcade','shoot','classic'],        featured:false, trending:false, isNew:false, plays:55000,  rating:4.3, likes:3100,  src:BASE+'87-duck-shooter.html',        emoji:'🦆', color:'#16a34a', desc:'Classic duck hunt game! Shoot as many ducks as you can before time runs out.',                   controls:'Mouse to aim | Click to shoot',thumb:'assets/thumbs/duck-shooter.jpg' },
  { id:'color-switch',    slug:'color-switch',    title:'Color Switch',         category:'arcade',    tags:['arcade','color','reflex'],         featured:false, trending:false, isNew:false, plays:45000,  rating:4.3, likes:2700,  src:BASE+'colorswitch.html',            emoji:'🎨', color:'#ec4899', desc:'Switch your color to pass through matching barriers! Fast reflexes needed.',                     controls:'Click / SPACE to switch color',thumb:'assets/thumbs/color-switch.jpg' },
  { id:'meteor-dodge',    slug:'meteor-dodge',    title:'Meteor Dodge',         category:'action',    tags:['action','space','dodge'],          featured:false, trending:false, isNew:true,  plays:31000,  rating:4.2, likes:1600,  src:BASE+'99-meteor-dodge.html',        emoji:'☄️', color:'#7c3aed', desc:'Dodge incoming meteors in space! How long can you survive the meteor shower?',                  controls:'Mouse / Touch to move',thumb:'assets/thumbs/meteor-dodge.jpg' },
  { id:'racing-game',     slug:'racing-game',     title:'Racing Game',          category:'arcade',    tags:['arcade','racing','cars'],          featured:false, trending:true,  isNew:false, plays:107000, rating:4.5, likes:6400,  src:BASE+'racinggame.html',             emoji:'🏎️', color:'#ef4444', desc:'Hit the track and race to the finish! Drift around corners and overtake rivals.',                controls:'← → Steer | ↑ Accelerate | ↓ Brake', thumb:'assets/thumbs/racing-game.jpg' },
  { id:'quiz-master',     slug:'quiz-master',     title:'Quiz Master',          category:'edu',       tags:['edu','quiz','trivia'],             featured:false, trending:false, isNew:false, plays:42000,  rating:4.3, likes:2300,  src:BASE+'quizmaster.html',             emoji:'❓', color:'#8b5cf6', desc:'Test your knowledge with hundreds of trivia questions! Multiple categories.',                    controls:'Click the correct answer',thumb:'assets/thumbs/quiz-master.jpg' },
  { id:'emoji-quest',     slug:'emoji-quest',     title:'Emoji Quest',          category:'puzzle',    tags:['puzzle','emoji','kids'],           featured:false, trending:true,  isNew:true,  plays:64000,  rating:4.5, likes:3900,  src:BASE+'100-emoji-quest.html',        emoji:'😄', color:'#f59e0b', desc:'Decode emoji puzzles and riddles! A fun challenge for all ages.',                               controls:'Click emojis to select answers',thumb:'assets/thumbs/emoji-quest.jpg' },

  // ── KIDS ────────────────────────────────────────────────────────────────────
  { id:'dino-jump',       slug:'dino-jump',       title:'Dinosaur Jump',        category:'kids',      tags:['kids','dinosaur','runner'],        featured:true,  trending:true,  isNew:false, plays:110000, rating:4.6, likes:7100,  src:BASE+'dinosaurjump.html',           emoji:'🦖', color:'#84cc16', desc:'The classic Chrome dinosaur game! Run endlessly and jump over cacti. 3 lives!',                 controls:'SPACE / ↑ to jump | Double jump allowed!',thumb:'assets/thumbs/dino-jump.jpg', thumb:'assets/thumbs/dinosaur-jump.jpg' },
  { id:'dino-world',      slug:'dino-world',      title:'Dino World',           category:'kids',      tags:['kids','dinosaur','runner'],        featured:false, trending:true,  isNew:false, plays:93000,  rating:4.6, likes:6200,  src:BASE+'35-dino-world.html',          emoji:'🦕', color:'#65a30d', desc:'Join the friendly dinosaur adventure! Jump over obstacles and collect gems.',                   controls:'SPACE / ↑ to jump', thumb:'assets/thumbs/dino-world.jpg' },
  { id:'fruit-catch',     slug:'fruit-catch',     title:'Fruit Catch',          category:'kids',      tags:['kids','fruits','catch'],           featured:false, trending:false, isNew:false, plays:67000,  rating:4.4, likes:3900,  src:BASE+'fruitcatch.html',             emoji:'🍎', color:'#dc2626', desc:'Catch falling fruits in your basket! Miss too many and it\'s game over.',                      controls:'← → / Mouse to move basket',thumb:'assets/thumbs/fruit-catch.jpg' },
  { id:'bubble-pop',      slug:'bubble-pop',      title:'Bubble Pop',           category:'kids',      tags:['kids','bubbles','pop'],            featured:false, trending:false, isNew:false, plays:54000,  rating:4.3, likes:3100,  src:BASE+'bubblepop.html',              emoji:'🫧', color:'#0ea5e9', desc:'Pop all the colorful bubbles! Simple, relaxing fun for all ages.',                              controls:'Click / tap bubbles to pop',thumb:'assets/thumbs/bubble-pop.jpg' },
  { id:'catch-stars',     slug:'catch-stars',     title:'Catch Stars',          category:'kids',      tags:['kids','stars','catch'],            featured:false, trending:false, isNew:false, plays:43000,  rating:4.2, likes:2300,  src:BASE+'catchstars.html',             emoji:'⭐', color:'#f59e0b', desc:'Catch falling stars before they hit the ground! Score as many as you can.',                     controls:'← → / Mouse to move',thumb:'assets/thumbs/catch-stars.jpg' },
  { id:'lucky-fishing',   slug:'lucky-fishing',   title:'Lucky Fishing',        category:'kids',      tags:['kids','fishing','relaxed'],        featured:false, trending:false, isNew:true,  plays:28000,  rating:4.1, likes:1400,  src:BASE+'95-lucky-fishing.html',       emoji:'🎣', color:'#0ea5e9', desc:'Cast your line and reel in fish! Relax and enjoy a peaceful fishing game.',                     controls:'Click to cast and reel in',thumb:'assets/thumbs/lucky-fishing.jpg' },
  { id:'cat-catcher',     slug:'cat-catcher',     title:'Cat Catcher',          category:'kids',      tags:['kids','cats','casual'],            featured:false, trending:false, isNew:true,  plays:22000,  rating:4.0, likes:1100,  src:BASE+'92-cat-catcher.html',         emoji:'🐱', color:'#f97316', desc:'Help the kitten catch yarn balls! A cute and fun game for young kids.',                         controls:'Click / tap to catch',thumb:'assets/thumbs/cat-catcher.jpg' },
  { id:'balloon-pop',     slug:'balloon-pop',     title:'Balloon Pop',          category:'kids',      tags:['kids','balloon','reflex'],         featured:false, trending:false, isNew:false, plays:36000,  rating:4.2, likes:2000,  src:BASE+'86-balloon-pop.html',         emoji:'🎈', color:'#ec4899', desc:'Pop balloons as they float up! Don\'t let any escape the screen.',                             controls:'Click / tap balloons',thumb:'assets/thumbs/balloon-pop.jpg' },
  { id:'memory-match',    slug:'memory-match',    title:'Memory Match',         category:'kids',      tags:['kids','memory','cards'],           featured:false, trending:false, isNew:false, plays:59000,  rating:4.5, likes:3400,  src:BASE+'memorymatch.html',            emoji:'🃏', color:'#8b5cf6', desc:'Find all matching pairs of cards! Great memory training game for kids.',                        controls:'Click cards to flip them',thumb:'assets/thumbs/memory-match.jpg' },
  { id:'candy-land',      slug:'candy-land',      title:'Candy Land',           category:'kids',      tags:['kids','candy','adventure'],        featured:false, trending:true,  isNew:false, plays:76000,  rating:4.5, likes:4500,  src:BASE+'40-candy-land.html',          emoji:'🍭', color:'#ec4899', desc:'Journey through a magical candy land! Collect sweets and dodge sugar monsters.',               controls:'Arrow keys to move',thumb:'assets/thumbs/candy-land.jpg' },
  { id:'robot-rescue',    slug:'robot-rescue',    title:'Robot Rescue',         category:'kids',      tags:['kids','robot','puzzle'],           featured:false, trending:false, isNew:false, plays:18000,  rating:4.0, likes:870,   src:BASE+'36-robot-rescue.html',        emoji:'🤖', color:'#6366f1', desc:'Save the trapped robots! Guide them safely through each level.',                                controls:'Arrow keys to guide robots',thumb:'assets/thumbs/robot-rescue.jpg' },
  { id:'underwater-adv',  slug:'underwater-adv',  title:'Underwater Adventure', category:'kids',      tags:['kids','ocean','adventure'],        featured:false, trending:false, isNew:false, plays:31000,  rating:4.2, likes:1600,  src:BASE+'42-underwater-adventure.html',emoji:'🐠', color:'#0ea5e9', desc:'Dive into an underwater world! Swim with sea creatures and collect treasures.',                 controls:'Arrow keys to swim',thumb:'assets/thumbs/underwater-adv.jpg' },
  { id:'sky-castle',      slug:'sky-castle',      title:'Sky Castle',           category:'adventure', tags:['adventure','castle','kids'],       featured:false, trending:false, isNew:false, plays:23000,  rating:4.1, likes:1100,  src:BASE+'34-sky-castle.html',          emoji:'🏰', color:'#7dd3fc', desc:'Explore a magical castle floating in the clouds! Find secret rooms and hidden treasure.',        controls:'Arrow keys to move and jump',thumb:'assets/thumbs/sky-castle.jpg' },

  // ── EDUCATION ────────────────────────────────────────────────────────────────
  { id:'math-blast',      slug:'math-blast',      title:'Math Blast',           category:'edu',       tags:['edu','math','kids'],               featured:false, trending:true,  isNew:false, plays:48000,  rating:4.5, likes:2800,  src:BASE+'56-math-blast.html',          emoji:'➕', color:'#06b6d4', desc:'Solve math problems before the timer runs out! Addition, subtraction and more.',                controls:'Type or click the correct answer',thumb:'assets/thumbs/math-blast.jpg' },
  { id:'letter-hunt',     slug:'letter-hunt',     title:'Letter Hunt',          category:'edu',       tags:['edu','letters','kids'],            featured:false, trending:false, isNew:false, plays:31000,  rating:4.3, likes:1700,  src:BASE+'57-letter-hunt.html',         emoji:'🔤', color:'#0ea5e9', desc:'Find and tap letters before they disappear! Great for learning the alphabet.',                  controls:'Click / tap the correct letters',thumb:'assets/thumbs/letter-hunt.jpg' },
  { id:'color-learn',     slug:'color-learn',     title:'Color Learn',          category:'edu',       tags:['edu','colors','toddler'],          featured:false, trending:false, isNew:false, plays:24000,  rating:4.4, likes:1300,  src:BASE+'58-color-learn.html',         emoji:'🌈', color:'#ec4899', desc:'Learn colors in a fun and interactive way! Perfect for young learners.',                        controls:'Click the matching color',thumb:'assets/thumbs/color-learn.jpg' },
  { id:'number-bubble',   slug:'number-bubble',   title:'Number Bubble',        category:'edu',       tags:['edu','numbers','kids'],            featured:false, trending:false, isNew:false, plays:27000,  rating:4.2, likes:1400,  src:BASE+'59-number-bubble.html',       emoji:'🔢', color:'#f59e0b', desc:'Pop number bubbles in the correct order! Count and learn while you play.',                      controls:'Click bubbles in number order',thumb:'assets/thumbs/number-bubble.jpg' },
  { id:'shape-sorter',    slug:'shape-sorter',    title:'Shape Sorter',         category:'edu',       tags:['edu','shapes','toddler'],          featured:false, trending:false, isNew:false, plays:19000,  rating:4.1, likes:980,   src:BASE+'60-shape-sorter.html',        emoji:'🔷', color:'#8b5cf6', desc:'Sort shapes into the correct holes! Circles, squares, triangles and more.',                     controls:'Drag shapes to matching holes',thumb:'assets/thumbs/shape-sorter.jpg' },
  { id:'word-build',      slug:'word-build',      title:'Word Builder',         category:'edu',       tags:['edu','words','spelling'],          featured:false, trending:false, isNew:false, plays:22000,  rating:4.2, likes:1150,  src:BASE+'61-word-build.html',          emoji:'📝', color:'#06b6d4', desc:'Build words from scrambled letters! Improve your spelling skills.',                             controls:'Drag letters to build words',thumb:'assets/thumbs/word-build.jpg' },
  { id:'count-stars',     slug:'count-stars',     title:'Count the Stars',      category:'edu',       tags:['edu','counting','kids'],           featured:false, trending:false, isNew:false, plays:16000,  rating:4.0, likes:780,   src:BASE+'62-count-stars.html',         emoji:'⭐', color:'#f59e0b', desc:'Count the stars on screen and choose the right number! Fun counting practice.',                 controls:'Click the correct number',thumb:'assets/thumbs/count-stars.jpg' },
  { id:'fraction-fun',    slug:'fraction-fun',    title:'Fraction Fun',         category:'edu',       tags:['edu','math','fractions'],          featured:false, trending:false, isNew:false, plays:14000,  rating:4.0, likes:680,   src:BASE+'63-fraction-fun.html',        emoji:'½', color:'#10b981', desc:'Learn fractions with pizza slices and fruit! Visual fraction learning made easy.',               controls:'Click the correct fraction',thumb:'assets/thumbs/fraction-fun.jpg' },
  { id:'time-teacher',    slug:'time-teacher',    title:'Time Teacher',         category:'edu',       tags:['edu','time','clocks'],             featured:false, trending:false, isNew:false, plays:18000,  rating:4.1, likes:880,   src:BASE+'64-time-teacher.html',        emoji:'🕐', color:'#f97316', desc:'Learn to read analog clocks! Match the time shown to the correct answer.',                      controls:'Click the matching time',thumb:'assets/thumbs/time-teacher.jpg' },
  { id:'spell-bee',       slug:'spell-bee',       title:'Spell Bee',            category:'edu',       tags:['edu','spelling','words'],          featured:false, trending:true,  isNew:false, plays:36000,  rating:4.4, likes:2100,  src:BASE+'65-spell-bee.html',           emoji:'🐝', color:'#f59e0b', desc:'Compete in a spelling bee! Hear the word and type the correct spelling.',                       controls:'Type the spelled word and press Enter',thumb:'assets/thumbs/spell-bee.jpg' },

  // ── SIMULATION ───────────────────────────────────────────────────────────────
  { id:'farm-grow',       slug:'farm-grow',       title:'Farm Grow',            category:'sim',       tags:['sim','farm','kids'],               featured:false, trending:false, isNew:false, plays:53000,  rating:4.4, likes:3200,  src:BASE+'66-farm-grow.html',           emoji:'🌾', color:'#65a30d', desc:'Grow your own farm! Plant crops, water them and harvest for profit.',                           controls:'Click to plant, water and harvest',thumb:'assets/thumbs/farm-grow.jpg' },
  { id:'city-builder',    slug:'city-builder',    title:'City Builder',         category:'sim',       tags:['sim','city','strategy'],           featured:false, trending:true,  isNew:false, plays:71000,  rating:4.5, likes:4300,  src:BASE+'67-city-builder.html',        emoji:'🏙️', color:'#6366f1', desc:'Build your own city from scratch! Place buildings and keep your citizens happy.',               controls:'Click to place buildings',thumb:'assets/thumbs/city-builder.jpg' },
  { id:'aquarium-keeper', slug:'aquarium-keeper', title:'Aquarium Keeper',      category:'sim',       tags:['sim','fish','kids'],               featured:false, trending:false, isNew:false, plays:38000,  rating:4.3, likes:2100,  src:BASE+'68-aquarium-keeper.html',     emoji:'🐠', color:'#0ea5e9', desc:'Design and manage your own aquarium! Feed fish and keep the water clean.',                      controls:'Click to feed fish and manage tank',thumb:'assets/thumbs/aquarium-keeper.jpg' },
  { id:'cookie-factory',  slug:'cookie-factory',  title:'Cookie Factory',       category:'sim',       tags:['sim','cookies','idle'],            featured:false, trending:true,  isNew:false, plays:94000,  rating:4.6, likes:5700,  src:BASE+'69-cookie-factory.html',      emoji:'🍪', color:'#b45309', desc:'Run a cookie empire! Click to bake and unlock upgrades for your factory.',                      controls:'Click to bake | Buy upgrades',thumb:'assets/thumbs/cookie-factory.jpg' },
  { id:'space-colony',    slug:'space-colony',    title:'Space Colony',         category:'sim',       tags:['sim','space','strategy'],          featured:false, trending:false, isNew:false, plays:29000,  rating:4.2, likes:1500,  src:BASE+'70-space-colony.html',        emoji:'🌍', color:'#7c3aed', desc:'Build a colony on another planet! Manage resources and expand your base.',                      controls:'Click to build and manage',thumb:'assets/thumbs/space-colony.jpg' },
  { id:'pizza-chef',      slug:'pizza-chef',      title:'Pizza Chef',           category:'sim',       tags:['sim','cooking','kids'],            featured:false, trending:false, isNew:false, plays:44000,  rating:4.3, likes:2500,  src:BASE+'71-pizza-chef.html',          emoji:'🍕', color:'#dc2626', desc:'Run your own pizza restaurant! Take orders, cook and serve before time runs out.',              controls:'Click to take orders and cook',thumb:'assets/thumbs/pizza-chef.jpg' },
  { id:'garden-bloom',    slug:'garden-bloom',    title:'Garden Bloom',         category:'sim',       tags:['sim','garden','relax'],            featured:false, trending:false, isNew:true,  plays:21000,  rating:4.1, likes:1050,  src:BASE+'72-garden-bloom.html',        emoji:'🌸', color:'#ec4899', desc:'Design and grow a beautiful flower garden! Plant, water and watch it bloom.',                   controls:'Click to plant and tend flowers',thumb:'assets/thumbs/garden-bloom.jpg' },
  { id:'star-collector',  slug:'star-collector',  title:'Star Collector',       category:'sim',       tags:['sim','stars','space'],             featured:false, trending:false, isNew:false, plays:26000,  rating:4.0, likes:1200,  src:BASE+'73-star-collector.html',      emoji:'⭐', color:'#f59e0b', desc:'Collect falling stars and build constellations! A relaxing space experience.',                  controls:'Move mouse / touch to catch stars',thumb:'assets/thumbs/star-collector.jpg' },
  { id:'mine-digger',     slug:'mine-digger',     title:'Mine Digger',          category:'sim',       tags:['sim','mining','adventure'],        featured:false, trending:false, isNew:false, plays:33000,  rating:4.2, likes:1700,  src:BASE+'74-mine-digger.html',         emoji:'⛏️', color:'#78350f', desc:'Dig deep into the earth to find rare gems and minerals! Upgrade your tools.',                  controls:'Arrow keys to dig | Collect gems',thumb:'assets/thumbs/mine-digger.jpg' },
  { id:'toy-factory',     slug:'toy-factory',     title:'Toy Factory',          category:'sim',       tags:['sim','toys','idle'],               featured:false, trending:false, isNew:false, plays:17000,  rating:4.0, likes:820,   src:BASE+'75-toy-factory.html',         emoji:'🧸', color:'#f97316', desc:'Run a magical toy factory! Manufacture toys and fulfill orders before the holidays.',           controls:'Click to manufacture and ship toys',thumb:'assets/thumbs/toy-factory.jpg' },

  // ── STRATEGY ─────────────────────────────────────────────────────────────────
  { id:'tower-guard',     slug:'tower-guard',     title:'Tower Guard',          category:'strategy',  tags:['strategy','tower','defend'],       featured:false, trending:false, isNew:false, plays:35000,  rating:4.3, likes:1900,  src:BASE+'19-tower-guard.html',         emoji:'🗼', color:'#b45309', desc:'Defend your tower from waves of enemies! Build defenses and survive.',                          controls:'Click to place defenses',thumb:'assets/thumbs/tower-guard.jpg' },
  { id:'kingdom-defense', slug:'kingdom-defense', title:'Kingdom Defense',      category:'strategy',  tags:['strategy','tower','kingdom'],      featured:false, trending:true,  isNew:false, plays:67000,  rating:4.6, likes:4200,  src:BASE+'76-kingdom-defense.html',     emoji:'🏰', color:'#b45309', desc:'Defend your kingdom against waves of invaders! Place towers and cast spells.',                  controls:'Click to place towers | SPACE for spell',thumb:'assets/thumbs/kingdom-defense.jpg' },
  { id:'chess-rush',      slug:'chess-rush',      title:'Chess Rush',           category:'strategy',  tags:['strategy','chess','classic'],      featured:false, trending:false, isNew:false, plays:28000,  rating:4.2, likes:1500,  src:BASE+'77-chess-rush.html',          emoji:'♟️', color:'#374151', desc:'Speed chess with a twist! Make fast decisions to outsmart your opponent.',                      controls:'Click to select and move pieces',thumb:'assets/thumbs/chess-rush.jpg' },
  { id:'tower-stack',     slug:'tower-stack',     title:'Tower Stack',          category:'strategy',  tags:['strategy','stack','build'],        featured:false, trending:false, isNew:false, plays:41000,  rating:4.3, likes:2200,  src:BASE+'78-tower-stack.html',         emoji:'🗼', color:'#6366f1', desc:'Stack blocks to build the tallest tower! Keep your balance or it all falls down.',               controls:'Click / SPACE to drop blocks',thumb:'assets/thumbs/tower-stack.jpg' },
  { id:'resource-wars',   slug:'resource-wars',   title:'Resource Wars',        category:'strategy',  tags:['strategy','war','resources'],      featured:false, trending:false, isNew:false, plays:19000,  rating:4.0, likes:940,   src:BASE+'79-resource-wars.html',       emoji:'⚔️', color:'#dc2626', desc:'Gather resources and build an army! Defeat rivals and conquer the land.',                       controls:'Click to gather and build',thumb:'assets/thumbs/resource-wars.jpg' },
  { id:'ant-colony',      slug:'ant-colony',      title:'Ant Colony',           category:'strategy',  tags:['strategy','ants','sim'],           featured:false, trending:false, isNew:false, plays:24000,  rating:4.1, likes:1200,  src:BASE+'80-ant-colony.html',          emoji:'🐜', color:'#78350f', desc:'Build and manage a thriving ant colony! Dig tunnels and gather food.',                         controls:'Click to direct ants and dig',thumb:'assets/thumbs/ant-colony.jpg' },
  { id:'ship-battle',     slug:'ship-battle',     title:'Ship Battle',          category:'strategy',  tags:['strategy','naval','battle'],       featured:false, trending:true,  isNew:false, plays:52000,  rating:4.4, likes:2900,  src:BASE+'81-ship-battle.html',         emoji:'⚓', color:'#0ea5e9', desc:'Command a naval fleet in epic sea battles! Sink enemy ships before yours go down.',             controls:'Click to move and fire cannons',thumb:'assets/thumbs/ship-battle.jpg' },
  { id:'crystal-wars',    slug:'crystal-wars',    title:'Crystal Wars',         category:'strategy',  tags:['strategy','crystal','battle'],     featured:false, trending:false, isNew:false, plays:16000,  rating:3.9, likes:750,   src:BASE+'82-crystal-wars.html',        emoji:'💎', color:'#06b6d4', desc:'Battle for crystal control! Build armies and conquer crystal mines.',                           controls:'Click to select units and attack',thumb:'assets/thumbs/crystal-wars.jpg' },
  { id:'planet-conquest', slug:'planet-conquest', title:'Planet Conquest',      category:'strategy',  tags:['strategy','space','conquest'],     featured:false, trending:false, isNew:false, plays:22000,  rating:4.0, likes:1050,  src:BASE+'84-planet-conquest.html',     emoji:'🪐', color:'#7c3aed', desc:'Conquer planets across the galaxy! Send fleets and expand your space empire.',                   controls:'Click to send fleets between planets',thumb:'assets/thumbs/planet-conquest.jpg' },
  { id:'dragon-tamer',    slug:'dragon-tamer',    title:'Dragon Tamer',         category:'strategy',  tags:['strategy','dragons','adventure'],  featured:false, trending:false, isNew:false, plays:29000,  rating:4.2, likes:1600,  src:BASE+'85-dragon-tamer.html',        emoji:'🐲', color:'#dc2626', desc:'Capture and train dragons for battle! Build the ultimate dragon army.',                         controls:'Click to tame and command dragons',thumb:'assets/thumbs/dragon-tamer.jpg' },

  // ── ADVENTURE ────────────────────────────────────────────────────────────────
  { id:'cloud-hopper',    slug:'cloud-hopper',    title:'Cloud Hopper',         category:'adventure', tags:['adventure','platform','kids'],     featured:false, trending:false, isNew:false, plays:27000,  rating:4.1, likes:1300,  src:BASE+'31-cloud-hopper.html',        emoji:'☁️', color:'#7dd3fc', desc:'Hop across clouds in the sky! Jump from cloud to cloud without falling.',                       controls:'← → Move | SPACE Jump',thumb:'assets/thumbs/cloud-hopper.jpg' },
  { id:'cave-explorer',   slug:'cave-explorer',   title:'Cave Explorer',        category:'adventure', tags:['adventure','cave','explore'],      featured:false, trending:false, isNew:false, plays:23000,  rating:4.0, likes:1050,  src:BASE+'32-cave-explorer.html',       emoji:'⛏️', color:'#78350f', desc:'Explore mysterious caves full of gems and dangers. Collect all treasure!',                     controls:'Arrow keys to move',thumb:'assets/thumbs/cave-explorer.jpg' },
  { id:'space-walk',      slug:'space-walk',      title:'Space Walk',           category:'adventure', tags:['adventure','space','platform'],    featured:false, trending:false, isNew:false, plays:19000,  rating:4.0, likes:890,   src:BASE+'39-space-walk.html',          emoji:'👨‍🚀', color:'#6366f1', desc:'Walk on the moon and explore space stations! Collect oxygen tanks to survive.',               controls:'Arrow keys to move and jump',thumb:'assets/thumbs/space-walk.jpg' },
  { id:'pirate-cove',     slug:'pirate-cove',     title:'Pirate Cove',          category:'adventure', tags:['adventure','pirate','treasure'],   featured:false, trending:false, isNew:false, plays:31000,  rating:4.2, likes:1600,  src:BASE+'38-pirate-cove.html',         emoji:'🏴‍☠️', color:'#b45309', desc:'Sail the seven seas as a pirate! Collect treasure and defeat sea monsters.',                  controls:'← → Move | ↑ Jump | SPACE Attack',thumb:'assets/thumbs/pirate-cove.jpg' },
  { id:'snow-mountain',   slug:'snow-mountain',   title:'Snow Mountain',        category:'adventure', tags:['adventure','winter','slide'],      featured:false, trending:false, isNew:false, plays:17000,  rating:4.0, likes:780,   src:BASE+'44-snow-mountain.html',       emoji:'⛷️', color:'#7dd3fc', desc:'Ski down a snow mountain! Dodge trees and rocks as you speed downhill.',                       controls:'← → to steer',thumb:'assets/thumbs/snow-mountain.jpg' },

  // ── SPACE SHOOTER ────────────────────────────────────────────────────────────
  { id:'space-shooter',   slug:'space-shooter',   title:'Space Shooter',        category:'action',    tags:['action','space','shoot'],          featured:false, trending:false, isNew:false, plays:76000,  rating:4.4, likes:4300,  src:BASE+'spaceshooter.html',           emoji:'🛸', color:'#6366f1', desc:'Classic space shooter! Destroy alien ships and survive the onslaught.',                        controls:'← → Move | SPACE Shoot',thumb:'assets/thumbs/space-shooter.jpg' },

];

/* ── Helper functions ── */
function getGameById(id)       { return GAMES.find(g => g.id === id || g.slug === id); }
function getFeatured()         { return GAMES.filter(g => g.featured); }
function getTrending()         { return GAMES.filter(g => g.trending); }
function getNew()              { return GAMES.filter(g => g.isNew); }
function getByCategory(cat)    { return cat === 'all' ? GAMES : GAMES.filter(g => g.category === cat || g.tags.includes(cat)); }
function getRelated(game, n=6) { return GAMES.filter(g => g.id !== game.id && (g.category === game.category || g.tags.some(t => game.tags.includes(t)))).slice(0,n); }
function formatPlays(n)        { return n >= 1000 ? (n/1000).toFixed(1)+'k' : n; }

/* ── Recently played ── */
const RECENT_KEY = 'zm_recent';
function addRecent(id) {
  let arr = JSON.parse(localStorage.getItem(RECENT_KEY)||'[]');
  arr = [id, ...arr.filter(x=>x!==id)].slice(0,8);
  localStorage.setItem(RECENT_KEY, JSON.stringify(arr));
}
function getRecent() {
  return JSON.parse(localStorage.getItem(RECENT_KEY)||'[]').map(id=>GAMES.find(g=>g.id===id)).filter(Boolean);
}
